###
# fabioassuncao/docker-images
#
# Repository:    MariaDB
# Image:         CLI/Base
# Version:       10.2
# Strategy:      Based on mariadb:10.2
# Base distro:   debian:jessie
#
FROM mariadb:10.2

MAINTAINER Fábio Assunção <fabio23gt@gmail.com>
