#!/usr/bin/env bash

if [ "$ENABLE_XDEBUG" == "yes" ]; then
    echo "Enabling xdebug"
    docker-php-ext-enable xdebug
fi

# Start supervisord and services
printf " -----> Info: Launching supervisord...\n"
if [ $# -gt 0 ]; then
    exec gosu www-data "$@"
else
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi