###
# fabioassuncao/docker-images
#
# Repository:    MariaDB
# Image:         CLI/Base
# Version:       10.3
# Strategy:      Based on mariadb:10.3
# Base distro:   debian:jessie
#
FROM mariadb:10.3

MAINTAINER Fábio Assunção <fabio23gt@gmail.com>
