###
# codions/docker-images
# Redis 3.2 official image (alpine build)
###
FROM redis:3.2-alpine

MAINTAINER Fábio Assunção <fabio23gt@gmail.com>

# Expose redis port
EXPOSE 6379

# Main command
CMD redis-server
