###
# fabioassuncao/docker-images
#
# Repository:    MariaDB
# Image:         CLI/Base
# Version:       5.5
# Strategy:      Based on mariadb:5.5
# Base distro:   debian:wheezy
#
FROM mariadb:5.5

MAINTAINER Fábio Assunção <fabio23gt@gmail.com>
